hyperparameters:
  client:
    batch_size: 10
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.8
    scheduler:
      gamma: 0.995
      step_size: 10
  model: Shakespeare_LSTM
  server:
    weighted: true
name: fedavg
