# Hyperparameters (HPs) of the algorithm
# Please refer to the algorithm's file to know which are the HPs 
hyperparameters:
  # HPs of the clients
  client:
    # Batch size
    batch_size: 10
    # Number of local epochs
    local_epochs: 5
    # The loss function
    loss: CrossEntropyLoss
    # HPs of the optimizer (the type of optimizer depends on the algorithm)
    optimizer:
      lr: 0.8
    # HPs of the StepLR
    scheduler:
      gamma: 0.995
      step_size: 10
  model: Shakespeare_LSTM
  # HPs of the server
  server:
    # whether to weight the client's contribution
    weighted: true
name: fl_bench.algorithms.fedavg.FedAVG
