data:
  client_split: 0
  dataset:
    name: mnist
    params: null
  distribution:
    name: iid
    params: null
  sampling_perc: 1
  standardize: false
exp:
  average: micro
  device: cpu
  seed: 42
logger:
  name: local
  params: null
protocol:
  eligible_perc: 1
  n_clients: 100
  n_rounds: 100
