data:
  client_split: 0.2
  dataset:
    name: femnist
  distribution:
    name: iid
  sampling_perc: 1
  standardize: false
exp:
  device: cpu
  seed: 42
logger:
  name: wandb
  entity: mlgroup
  project: fluke
protocol:
  eligible_perc: 0.007
  n_clients: 730
  n_rounds: 100
