data:
  client_split: 0.1
  dataset:
    name: mnist
  distribution:
    name: iid
  sampling_perc: 1
  standardize: false
exp:
  device: cpu
  seed: 42
logger:
  name: local
protocol:
  eligible_perc: 0.1
  n_clients: 100
  n_rounds: 50
