hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01
    scheduler:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    beta1: 0.9
    beta2: 0.999
    lr: 0.01
    mode: adagrad
    tau: 0.001
name: fl_bench.algorithms.fedopt.FedOpt
