hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01
      weight_decay: 0.0001
    scheduler_kwargs:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    momentum: 0.9
name: fl_bench.algorithms.fedavgm.FedAVGM
