hyperparameters:
  client:
    batch_size: 10
    local_epochs: 5
    loss: CrossEntropyLoss
    model: MNIST_CNN_E
    n_protos: 10
    optimizer:
      lr: 0.01
      momentum: 0.9
      # weight_decay: 0.0001
    scheduler:
      name: ExponentialLR
      gamma: 0.99
  model: MNIST_CNN_E
  server:
    n_protos: 10
    weighted: false
    rho: 0.9
name: fluke.algorithms.fednh.FedNH
