hyperparameters:
  client:
    batch_size: 64
    local_epochs: 5
    loss: CrossEntropyLoss
    model: MNIST_2NN_ED
    optimizer:
      lr: 0.1
      momentum: 0.9
    relative: false
    scheduler:
      gamma: 1
      step_size: 1
    tau: 50
  model: MNIST_2NN_D
  server:
    n_anchors: 200
    seed_anchors: 98765
name: fluke.algorithms.flhalf.FLHalf
