hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    mu: 1
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
    tau: 0.5
  model: MNIST_2NN_Proto
  server:
    weighted: true
name: fluke.algorithms.moon.MOON
