# Dataset configuration
data:
  # Dataset loading config
  dataset:
    # Dataset's name 
    # Currently supported: mnist, svhn, mnistm, femnist, emnist, cifar10, cifar100, tiny_imagenet,
    #                      shakespeare, fashion_mnist, cinic10
    name: mnist
    # Potential parameters for loading the dataset correctly (see fluke.data.datasets)
    params: null
  # IID/non-IID data distribution
  distribution:
    # Currently supported: 
    # - iid: Independent and Identically Distributed data.
    # - qnt: Quantity skewed data.
    # - classqnt: Class-wise quantity skewed data.
    # - lblqnt: Label quantity skewed data.
    # - dir: Label skewed data according to the Dirichlet distribution.
    # - path : Pathological skewed data (each client has data from a small subset of the classes).
    # - covshift: Covariate shift skewed data.
    name: iid
    # Potential parameters of the disribution, e.g., `beta` for `dir`
    params: null
  # Sampling percentage when loading the dataset
  sampling_perc: 1
  # Client-side test set split percentage
  client_split: 0
  # Whether to keep the test set as provided by the dataset
  keep_test: true
  # Whether the server has a test set
  server_test: true
  # The size of the server split (only used when keep_test=false)
  server_split: 0.0
# Generic settings for the experiment
exp:
  # The device to load the tensors
  device: cpu
  # The seed (reproducibility)
  seed: 42
# Logger configuration
logger:
  # `local` is the standard output, `wandb` log everything on weights and bias
  name: local
  # `wand` parameters
  params: null
# FL protocol configuration
protocol:
  # % of eligible clients in each round
  eligible_perc: 1
  # Total number of clients partcipating in the federation
  n_clients: 100
  # Total number of rounds
  n_rounds: 100
