data:
  client_split: 0.1
  dataset:
    name: mnist
    path: ./data
  distribution:
    name: iid
  sampling_perc: 1
exp:
  device: cpu
  seed: 42
logger:
  name: Log
protocol:
  eligible_perc: 0.1
  n_clients: 100
  n_rounds: 50
