hyperparameters:
  client:
    batch_size: 32
    lam: 0.1
    local_epochs: 5
    loss: CrossEntropyLoss
    model: MNIST_2NN
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    tau: 1
    weighted: true
  model: MNIST_2NN
name: fluke.algorithms.apfl.APFL
