# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: cifar10
    path: ./data
  distribution:
    name: lbl_qnt
    class_per_client: 1
  sampling_perc: 1
  client_split: 0.2
  keep_test: true
  server_test: true
  server_split: 0.0 
  uniform_test: false
exp:
  device: cuda
  seed: 8
eval:
  task: classification
  eval_every: 10
  pre_fit: true
  post_fit: true
logger:
  name: Log
  project: fluke_benchmarks
  tags: [FedAwS]
protocol:
  eligible_perc: 1
  n_clients: 10
  n_rounds: 1000