# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: emnist
    path: ./data
  distribution:
    name: iid
  sampling_perc: 1
  client_split: 0.2
  keep_test: true
  server_test: true
  server_split: 0.0 # not used in this case
  uniform_test: false
exp:
  device: cpu
  seed: 42
eval:
  task: classification
  eval_every: 1
  pre_fit: true
  post_fit: false
logger:
  name: WandBLog
  # name: WandBLog
  project: fluke_benchmarks
  # entity: mlgroup
protocol:
  eligible_perc: 0.2
  n_clients: 100
  n_rounds: 100
