# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: cifar10
    path: ./data
  distribution:
    name: dir
    beta: 0.1
  sampling_perc: 1
  client_split: 0.2
  keep_test: true
  server_test: true
  server_split: 0.0 # not used in this case
  uniform_test: false
exp:
  device: cuda
  seed: 57
eval:
  task: classification
  eval_every: 1
  pre_fit: true
  post_fit: true
logger:
  name: WandBLog
  project: fluke_benchmarks
  tags: [FedAdam]
protocol:
  eligible_perc: 0.1
  n_clients: 500
  n_rounds: 2500 #ne richiede 4k ma mi sono stufato