# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: cifar10
    path: ./data
  distribution:
    name: dir
    beta: 0.5
  sampling_perc: 1
  client_split: 0
  keep_test: true
  server_test: true 
  server_split: 0.0
  uniform_test: false
exp:
  device: cuda
  seed: 42
eval:
  task: classification
  eval_every: 1
  pre_fit: true
  post_fit: true
logger:
  name: WandBLog
  project: fluke_benchmarks
  tags: [FedNova]
protocol:
  eligible_perc: 1
  n_clients: 20
  n_rounds: 400