hyperparameters:
  client:
    batch_size: 10
    local_epochs: 1
    loss: CrossEntropyLoss
    ala_sample_size: 0.8 # 80% of the data is used for ALA
    loss_window_size: 1 # what 
    optimizer:
      lr: 0.005
      # momentum: 0.9
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: MNIST_CNN
name: fluke.algorithms.fedala.FedALA
