hyperparameters:
  client:
    batch_size: 50
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.1
  server:
    mode: adam
    tau: 0.000001
  model: CIFAR10_CNN.CIFAR_CNN
name: fluke.algorithms.fedopt.FedOpt
