hyperparameters:
  client:
    batch_size: 10
    lam: 0.1
    local_epochs: 5
    loss: CrossEntropyLoss
    model: MNIST_2NN
    optimizer:
      lr: 0.1
    scheduler:
      gamma: 1
      step_size: 1
  server:
    alpha: 0.1
    sigma: 1
  model: MNIST_2NN
name: fluke.algorithms.fedamp.FedAMP
