hyperparameters:
  client:
    batch_size: 32
    local_epochs: 5
    loss: CrossEntropyLoss
    margin_lam: 0.2
    optimizer:
      lr: 0.1
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    momentum: 0.9
  model: MNIST_2NN
name: fluke.algorithms.fedmargin.FedAVGMMargin
