hyperparameters:
  client:
    batch_size: 10
    lam: 0.1
    local_epochs: 1
    loss: CrossEntropyLoss
    model: MNIST_2NN_E
    n_protos: 10
    optimizer:
      lr: 0.01
    scheduler:
      gamma: 1
      step_size: 1
  server:
    n_protos: 10
    weighted: true
    embedding_size: 200
  model: MNIST_2NN_E
name: fluke.algorithms.fedhp.FedHP
