hyperparameters:
  client:
    batch_size: 64
    local_epochs: 10
    loss: CrossEntropyLoss
    mu: 5 # abbassare per ridurre carico computazionale?
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.00001
    scheduler:
      gamma: 1
      step_size: 1
    tau: 0.5 # temperature
  server:
    weighted: true
  model: mooncnnv2.MoonCNN
name: fluke.algorithms.moon.MOON
