hyperparameters:
  client:
    batch_size: 32
    local_epochs: 2
    loss: CrossEntropyLoss
    mu: 0.005
    scheduler:
      name: MultiStepLR
      milestones: [50,75]
      gamma: 1
    optimizer:
      lr: 0.02
      momentum: 0.9
  server:
    weighted: true
  model: vgg11.VGG11
name: fluke.algorithms.fednova.FedNova