hyperparameters:
  client:
    batch_size: 32
    local_epochs: 2
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.1
      momentum: 0.9
      # weight_decay: 0.0001
    scheduler:
      name: MultiStepLR
      milestones: [50]
      gamma: 0.1
  server:
    weighted: true
  model: vgg11.VGG11
name: fluke.algorithms.fednova.FedNova