hyperparameters:
  client:
    batch_size: 128
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: ResNet18
name: fluke.algorithms.fednova.FedNova