hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    model: MNIST_2NN
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    scheduler:
      gamma: 0.995
      step_size: 10
  server:
    weighted: true
  model: MNIST_2NN_E
name: fluke.algorithms.fedper.FedPer
