hyperparameters:
  client:
    batch_size: 0
    local_epochs: 1
    loss: CrossEntropyLoss
    optimizer:
      lr: 1.5
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: MNIST_2NN
name: fluke.algorithms.fedsgd.FedSGD
