hyperparameters:
  client:
    batch_size: 10
    local_epochs: 50
    loss: CrossEntropyLoss
    mu: 1
    optimizer:
      lr: 0.03
      # momentum: 0.9
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: MNIST_LR
name: fluke.algorithms.fedprox.FedProx
